# Generated by Django 2.2.5 on 2021-01-25 09:58

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('generated_OTP', models.IntegerField(default=0)),
                ('received_OTP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('product_description', models.CharField(default='', max_length=500)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_listed_date', models.DateField()),
                ('product_quantity', models.FloatField(default=0.0)),
                ('product_quantity_per_serving_gms', models.FloatField(default=0.0)),
                ('product_image', models.ImageField(default='', upload_to='greeban/images')),
                ('product_prof_image', models.ImageField(default='', upload_to='greeban/images')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=255)),
                ('pin', models.IntegerField(default=0)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('mobile_no', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='greeban.OTP')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('itemsAndQuantity', picklefield.fields.PickledObjectField(editable=False)),
                ('price', picklefield.fields.PickledObjectField(editable=False)),
                ('total_amount', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greeban.OTP')),
            ],
        ),
    ]
