# Generated by Django 3.1.7 on 2021-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0003_auto_20210207_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
    ]
