# Generated by Django 3.1.7 on 2021-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0004_auto_20210227_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
