# Generated by Django 3.1.7 on 2021-03-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0005_auto_20210228_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='itemsAndQuantity',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_details_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='greeban.product'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(default='', max_length=100, unique=True)),
                ('transaction_status', models.CharField(choices=[('Initiated', 'In progress'), ('created', 'Transaction Created'), ('Success', 'Transaction Completed'), ('failed', 'Transaction Failed')], default='', max_length=20)),
                ('name', models.CharField(default='', max_length=40)),
                ('contactNo', models.CharField(default='', max_length=10)),
                ('emailId', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=40)),
                ('state', models.CharField(default='', max_length=30)),
                ('pinCode', models.CharField(default='', max_length=7)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='greeban.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='greeban.order'),
        ),
    ]
