# Generated by Django 3.1.7 on 2021-03-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0006_auto_20210302_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promocode_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('promocode', models.CharField(default=0, max_length=20)),
                ('discount_percent', models.IntegerField(default=0)),
                ('times_used', models.IntegerField(default=1)),
            ],
        ),
    ]
