# Generated by Django 3.1.7 on 2021-03-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0007_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='influencer_email',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
