# Generated by Django 2.2.5 on 2020-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_description', models.CharField(default='', max_length=500)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_listed_date', models.DateField()),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='', upload_to='greeban/images')),
            ],
        ),
    ]
