# Generated by Django 3.1.2 on 2020-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_prof_image',
            field=models.ImageField(default='', upload_to='greeban/images'),
        ),
    ]
