# Generated by Django 2.2.5 on 2020-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeban', '0002_product_product_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
